### ISSUE TITLE
About split_pcl2pcl.txt

### ISSUE THREAD

**Issue by ZhiXia-SEU** [a4152684/KT-Net#1]
Thanks for your good work，Can you provide the file "split_pcl2pcl.txt" in dataloader? Thanks a lot!

**Comment by a4152684** [comment]
Thank you for your attention. This file is now in "dataset" folder. https://github.com/a4152684/KT-Net/blob/main/dataset/split_pcl2pcl.txt

**Comment by ZhiXia-SEU** [comment]
Thanks！It is of great helpful!
